[DEFAULT]
PUBLIC_ROUTES = ["iems.auth.login","iems.files.save_file","iems.files.get_file","iems.students.extract_aadhaar","iems.students.extract_result"]
BRANCH_LIST = ["CSD","Computer Science & Design"]
[DEV]
SERVER_HOST = "localhost"
SERVER_PORT = 8000
POSTGRES_MIN_CONN = 1
POSTGRES_MAX_CONN = 2

[PROD]
SERVER_HOST = "0.0.0.0"
SERVER_PORT = 10000
POSTGRES_MIN_CONN = 1
POSTGRES_MAX_CONN = 4
